import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    { type: 'autogenerated', dirName: '.', },
    {
      type: 'category',
      label: 'Others',
      items: [
        {
          type: 'link',
          label: 'llms.txt',
          href: '/llms.txt',
        },
        // {
        //   type: 'link',
        //   label: 'GitHub',
        //   href: 'https://github.com/AnyFlowLabs',
        // },
        // {
        //   type: 'link',
        //   label: 'Discord',
        //   href: 'https://discord.com/invite/aCygGwBWya',
        // },
        // {
        //   type: 'link',
        //   label: 'Twitter',
        //   href: 'https://x.com/anyflow_',
        // },
      ],
    },
  ],
};

export default sidebars;
