import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    { type: 'autogenerated', dirName: '.', },
    {
      type: 'category',
      label: 'Others',
      items: [
        {
          // Note: this is a workaround to open the llms.txt file in a new tab and
          // prevent navigation issues
          type: 'html',
          value: '<a class="menu__link" href="/llms.txt" target="_blank">llms.txt</a>',
          defaultStyle: true,
        },
      ],
    },
  ],
};

export default sidebars;
